# Generated by Django 3.1.4 on 2021-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Fuel',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Gasoline', 'Gasoline'), ('Hybrid', 'Hybrid'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=30, null=True),
        ),
    ]
